In [6]:
import pandas as pd
import GetOldTweets3 as got
# https://github.com/Mottl/GetOldTweets3

In [7]:
def get_twitter_info():
    tweet_df["id"] = tweet_df["got_criteria"].apply(lambda x: x.id)
    tweet_df["tweet_text"] = tweet_df["got_criteria"].apply(lambda x: x.text)
    tweet_df["timestamp"] = tweet_df["got_criteria"].apply(lambda x: x.date)
    tweet_df["hashtags"] = tweet_df["got_criteria"].apply(lambda x: x.hashtags)
    tweet_df["username"] = tweet_df["got_criteria"].apply(lambda x: x.username)
    tweet_df["mentions"] = tweet_df["got_criteria"].apply(lambda x: x.mentions)
    tweet_df["rewtweets"] = tweet_df["got_criteria"].apply(lambda x: x.retweets)
    tweet_df["replies"] = tweet_df["got_criteria"].apply(lambda x: x.replies)
    tweet_df["link"] = tweet_df["got_criteria"].apply(lambda x: x.permalink)
# https://medium.com/@robbiegeoghegan/download-twitter-data-with-10-lines-of-code-42eb2ba1ab0f

In [17]:
#set search variables
# keyword = "fire, #campfire, wildfires"
# oldest_date = "2018-11-07"    
# newest_date = "2018-11-15"
locations = ["Chico, CA"]
# number_tweets = 10         #per location

#get old tweets
tweetCriteria_list = []
for location in locations:
    tweetCriteria = got.manager.TweetCriteria().setSince('2018-11-07')\
                                            .setUntil('2018-11-26')\
                                            .setNear(location)\
                                            .setWithin('100mi')
#                                             .setMaxTweets(number_tweets)\
#                                             .setQuerySearch(keyword)\
    tweetCriteria_list.append(tweetCriteria)
    
#create twitter info for each city
tweet_dict = {}
for criteria, location in zip(tweetCriteria_list, locations):
    tweets = got.manager.TweetManager.getTweets(criteria)
    tweet_dict[location] = tweets
    
#create df
tweet_df = pd.DataFrame(dict([ (k,pd.Series(v)) for k,v in tweet_dict.items() ]))
tweet_df['tweet_count'] = tweet_df.index
tweet_df = pd.melt(tweet_df, id_vars=["tweet_count"], var_name='City', value_name='got_criteria')
# tweet_df = tweet_df.dropna()

#extract twitter information
get_twitter_info()
tweet_df = tweet_df.drop("got_criteria", 1)
tweet_df.head()

,tweet_count,City,id,tweet_text,timestamp,hashtags,username,mentions,rewtweets,replies,link
0,0,"Chico, CA",1066843491555205120,"Lord Farquad Quad Squat Squad @Chico, Californ...",2018-11-25 23:58:04+00:00,,areoandmilk,,0,0,https://twitter.com/areoandmilk/status/1066843...
1,1,"Chico, CA",1066842521601400832,winter edition #queenadailypic released. @Soda...,2018-11-25 23:54:12+00:00,#queenadailypic,leenathequeena,,0,0,https://twitter.com/leenathequeena/status/1066...
2,2,"Chico, CA",1066841740060098562,Drinking a Def Leppard Pale by @ElysianBrewing...,2018-11-25 23:51:06+00:00,,geradellsworth,@ElysianBrewing @Golden1Center,0,0,https://twitter.com/geradellsworth/status/1066...
3,3,"Chico, CA",1066841178782482433,"The forgotten. #LimeBike #Reno @Reno, Nevada h...",2018-11-25 23:48:52+00:00,#LimeBike #Reno,alittlegordie,,0,0,https://twitter.com/alittlegordie/status/10668...
4,4,"Chico, CA",1066839617196961792,SSCC is United and moving Forward !!! The powe...,2018-11-25 23:42:40+00:00,#heritageoffaith,LesSimmons,@sscc7710,1,0,https://twitter.com/LesSimmons/status/10668396...

In [18]:
chico = tweet_df.copy()
chico.shape

(811, 11)

In [19]:
chico.to_csv('./data/chico.csv', index=False)

In [25]:
## dataframes
# paradise (817, 11)
# butte (902, 11)
# chico (811, 11)
# sacramento (6007, 11)

In [21]:
butte.shape

(902, 11)

In [22]:
df = pd.concat([paradise, butte, chico, sacramento])
df.shape

(8537, 11)

In [33]:
df.to_csv('./data/df_with_dups.csv', index=False)

In [32]:
dups = df[(df['id'].duplicated() == True)]
dups

df.sort_values("id", inplace = True) 
df.drop_duplicates(subset ="id", 
                     keep = 'first', inplace = True) 
df.shape

dups = df[(df['id'].duplicated() == True)]
dups.shape

,tweet_count,City,id,tweet_text,timestamp,hashtags,username,mentions,rewtweets,replies,link
0,0,Butte County,1066843491555205120,"Lord Farquad Quad Squat Squad @Chico, Californ...",2018-11-25 23:58:04+00:00,,areoandmilk,,0,0,https://twitter.com/areoandmilk/status/1066843...
1,1,Butte County,1066842521601400832,winter edition #queenadailypic released. @Soda...,2018-11-25 23:54:12+00:00,#queenadailypic,leenathequeena,,0,0,https://twitter.com/leenathequeena/status/1066...
2,2,Butte County,1066841740060098562,Drinking a Def Leppard Pale by @ElysianBrewing...,2018-11-25 23:51:06+00:00,,geradellsworth,@ElysianBrewing @Golden1Center,0,0,https://twitter.com/geradellsworth/status/1066...
3,3,Butte County,1066841178782482433,"The forgotten. #LimeBike #Reno @Reno, Nevada h...",2018-11-25 23:48:52+00:00,#LimeBike #Reno,alittlegordie,,0,0,https://twitter.com/alittlegordie/status/10668...
5,5,Butte County,1066839617196961792,SSCC is United and moving Forward !!! The powe...,2018-11-25 23:42:40+00:00,#heritageoffaith,LesSimmons,@sscc7710,1,0,https://twitter.com/LesSimmons/status/10668396...
...,...,...,...,...,...,...,...,...,...,...,...
24,24,Sacramento,1066838579312246785,Stopped by last night to hang out with some fr...,2018-11-25 23:38:32+00:00,#bruco #taproom #graphics #localartist #smallb...,DblDownCreative,,0,0,https://twitter.com/DblDownCreative/status/106...
25,25,Sacramento,1066838431618207745,"Just posted a photo @Sacramento, California ht...",2018-11-25 23:37:57+00:00,,nicholechoice,,0,0,https://twitter.com/nicholechoice/status/10668...
26,26,Sacramento,1066837573807546368,"Just posted a photo @Sacramento, California ht...",2018-11-25 23:34:33+00:00,,nicholechoice,,0,0,https://twitter.com/nicholechoice/status/10668...
27,27,Sacramento,1066836849593917441,All the basics ... for a Sunday treat @Sacrame...,2018-11-25 23:31:40+00:00,,sabiovasquez,,0,0,https://twitter.com/sabiovasquez/status/106683...
28,28,Sacramento,1066836825677938688,"Just posted a video @Sacramento, California ht...",2018-11-25 23:31:34+00:00,,sabiovasquez,,0,0,https://twitter.com/sabiovasquez/status/106683...

In [37]:
df.to_csv('./data/df_cleaned.csv', index=False)

In [39]:
df.sort_values("tweet_count", inplace = True)

In [42]:
df.head()

,tweet_count,City,id,tweet_text,timestamp,hashtags,username,mentions,rewtweets,replies,link
0,0,Sacramento,1066843931114115072,#asianribs #friedrice #fallsoffthebone #meltsi...,2018-11-25 23:59:48+00:00,#asianribs #friedrice #fallsoffthebone #meltsi...,bgvino,,0,0,https://twitter.com/bgvino/status/106684393111...
1,1,Sacramento,1066843803686887424,Just posted a photo @Plaza De Cesar Chavez htt...,2018-11-25 23:59:18+00:00,,apmanzojr,,0,0,https://twitter.com/apmanzojr/status/106684380...
1,1,"Paradise, CA",1066842521601400832,winter edition #queenadailypic released. @Soda...,2018-11-25 23:54:12+00:00,#queenadailypic,leenathequeena,,0,0,https://twitter.com/leenathequeena/status/1066...
2,2,Sacramento,1066843491555205120,"Lord Farquad Quad Squat Squad @Chico, Californ...",2018-11-25 23:58:04+00:00,,areoandmilk,,0,0,https://twitter.com/areoandmilk/status/1066843...
2,2,"Chico, CA",1066841740060098562,Drinking a Def Leppard Pale by @ElysianBrewing...,2018-11-25 23:51:06+00:00,,geradellsworth,@ElysianBrewing @Golden1Center,0,0,https://twitter.com/geradellsworth/status/1066...

In [46]:
df['replies'].sort_values(ascending=False)

4087    10
1894     8
567      6
4488     6
669      5
        ..
3668     0
3669     0
3670     0
3671     0
0        0
Name: replies, Length: 6922, dtype: int64