In [1]:
import pandas as pd
import GetOldTweets3 as got
# https://github.com/Mottl/GetOldTweets3

In [2]:
def get_twitter_info():
    tweet_df["id"] = tweet_df["got_criteria"].apply(lambda x: x.id)
    tweet_df["tweet_text"] = tweet_df["got_criteria"].apply(lambda x: x.text)
    tweet_df["timestamp"] = tweet_df["got_criteria"].apply(lambda x: x.date)
    tweet_df["hashtags"] = tweet_df["got_criteria"].apply(lambda x: x.hashtags)
    tweet_df["username"] = tweet_df["got_criteria"].apply(lambda x: x.username)
    tweet_df["mentions"] = tweet_df["got_criteria"].apply(lambda x: x.mentions)
    tweet_df["rewtweets"] = tweet_df["got_criteria"].apply(lambda x: x.retweets)
    tweet_df["replies"] = tweet_df["got_criteria"].apply(lambda x: x.replies)
    tweet_df["link"] = tweet_df["got_criteria"].apply(lambda x: x.permalink)
# https://medium.com/@robbiegeoghegan/download-twitter-data-with-10-lines-of-code-42eb2ba1ab0f

In [18]:
#set search variables
# keyword = "fire, #campfire, wildfires"
# oldest_date = "2018-11-07"    
# newest_date = "2018-11-15"
locations = ["Durham, CA"]
# number_tweets = 10         #per location

#get old tweets
tweetCriteria_list = []
for location in locations:
    tweetCriteria = got.manager.TweetCriteria().setSince('2018-11-01')\
                                            .setUntil('2018-11-06')\
                                            .setNear(location)\
                                            .setWithin('100mi')
#                                             .setMaxTweets(number_tweets)\
#                                             .setQuerySearch(keyword)\
    tweetCriteria_list.append(tweetCriteria)
    
#create twitter info for each city
tweet_dict = {}
for criteria, location in zip(tweetCriteria_list, locations):
    tweets = got.manager.TweetManager.getTweets(criteria)
    tweet_dict[location] = tweets
    
#create df
tweet_df = pd.DataFrame(dict([ (k,pd.Series(v)) for k,v in tweet_dict.items() ]))
tweet_df['tweet_count'] = tweet_df.index
tweet_df = pd.melt(tweet_df, id_vars=["tweet_count"], var_name='City', value_name='got_criteria')
# tweet_df = tweet_df.dropna()

#extract twitter information
get_twitter_info()
tweet_df = tweet_df.drop("got_criteria", 1)
# tweet_df.head()

In [19]:
durham_pre = tweet_df.copy()
durham_pre.shape

(160, 11)

In [20]:
durham_pre.to_csv('./data/durham_pre.csv', index=False)

In [25]:
## dataframes
# paradise (817, 11)
# butte (902, 11)
# chico (811, 11)
# oroville (202, 11)
# magalia (764, 11)
# durham (862, 11)

# paradise_pre (145, 11)
# butte_pre (166, 11)
# chico_pre (141, 11)
# oroville_pre (53, 11)
# magalia_pre (144, 11)
# durham_pre (160, 11)


# sacramento (6007, 11)

In [21]:
butte.shape

(902, 11)

In [18]:
df = pd.concat([paradise, butte, chico, durham, magalia, oroville])
df.shape

NameError: name 'paradise' is not defined

In [33]:
# df.to_csv('./data/df_with_dups.csv', index=False)

In [21]:
# dups = df[(df['id'].duplicated() == True)]
# dups

# df.sort_values("id", inplace = True) 
# df.drop_duplicates(subset ="id", 
#                      keep = 'first', inplace = True) 
# df.shape

# dups = df[(df['id'].duplicated() == True)]
# dups.shape

In [37]:
df.to_csv('./data/df_cleaned.csv', index=False)

In [39]:
df.sort_values("tweet_count", inplace = True)

In [42]:
df.head()

,tweet_count,City,id,tweet_text,timestamp,hashtags,username,mentions,rewtweets,replies,link
0,0,Sacramento,1066843931114115072,#asianribs #friedrice #fallsoffthebone #meltsi...,2018-11-25 23:59:48+00:00,#asianribs #friedrice #fallsoffthebone #meltsi...,bgvino,,0,0,https://twitter.com/bgvino/status/106684393111...
1,1,Sacramento,1066843803686887424,Just posted a photo @Plaza De Cesar Chavez htt...,2018-11-25 23:59:18+00:00,,apmanzojr,,0,0,https://twitter.com/apmanzojr/status/106684380...
1,1,"Paradise, CA",1066842521601400832,winter edition #queenadailypic released. @Soda...,2018-11-25 23:54:12+00:00,#queenadailypic,leenathequeena,,0,0,https://twitter.com/leenathequeena/status/1066...
2,2,Sacramento,1066843491555205120,"Lord Farquad Quad Squat Squad @Chico, Californ...",2018-11-25 23:58:04+00:00,,areoandmilk,,0,0,https://twitter.com/areoandmilk/status/1066843...
2,2,"Chico, CA",1066841740060098562,Drinking a Def Leppard Pale by @ElysianBrewing...,2018-11-25 23:51:06+00:00,,geradellsworth,@ElysianBrewing @Golden1Center,0,0,https://twitter.com/geradellsworth/status/1066...

In [46]:
df['replies'].sort_values(ascending=False)

4087    10
1894     8
567      6
4488     6
669      5
        ..
3668     0
3669     0
3670     0
3671     0
0        0
Name: replies, Length: 6922, dtype: int64

In [20]:
paradise = pd.read_csv('./data/paradise.csv')
butte = pd.read_csv('./data/butte.csv')
chico = pd.read_csv('./data/chico.csv')
magalia = pd.read_csv('./data/magalia.csv')
oroville = pd.read_csv('./data/oroville.csv')

In [21]:
cities = pd.concat([paradise, butte, chico, durham, magalia, oroville])
cities.shape

(4358, 11)

In [22]:
cities.to_csv('./data/cities_raw.csv', index=False)

In [26]:
dups = cities[(cities['id'].duplicated() == True)]
dups

,tweet_count,City,id,tweet_text,timestamp,hashtags,username,mentions,rewtweets,replies,link
0,0,Butte County,1066843491555205120,"Lord Farquad Quad Squat Squad @Chico, Californ...",2018-11-25 23:58:04+00:00,NaN,areoandmilk,NaN,0,0,https://twitter.com/areoandmilk/status/1066843...
1,1,Butte County,1066842521601400832,winter edition #queenadailypic released. @Soda...,2018-11-25 23:54:12+00:00,#queenadailypic,leenathequeena,NaN,0,0,https://twitter.com/leenathequeena/status/1066...
2,2,Butte County,1066841740060098562,Drinking a Def Leppard Pale by @ElysianBrewing...,2018-11-25 23:51:06+00:00,NaN,geradellsworth,@ElysianBrewing @Golden1Center,0,0,https://twitter.com/geradellsworth/status/1066...
3,3,Butte County,1066841178782482433,"The forgotten. #LimeBike #Reno @Reno, Nevada h...",2018-11-25 23:48:52+00:00,#LimeBike #Reno,alittlegordie,NaN,0,0,https://twitter.com/alittlegordie/status/10668...
5,5,Butte County,1066839617196961792,SSCC is United and moving Forward !!! The powe...,2018-11-25 23:42:40+00:00,#heritageoffaith,LesSimmons,@sscc7710,1,0,https://twitter.com/LesSimmons/status/10668396...
...,...,...,...,...,...,...,...,...,...,...,...
196,196,"Oroville, CA",1060237957473464320,4th stop on #FarmCityWeek at Look Ahead Veteri...,2018-11-07 18:30:01+00:00,#FarmCityWeek #sacvalley,WCWDwebcam,NaN,0,0,https://twitter.com/WCWDwebcam/status/10602379...
197,197,"Oroville, CA",1060216596306620416,Morse Mandarin Farm visit on #FarmCityWeek tou...,2018-11-07 17:05:09+00:00,#FarmCityWeek #SacValley,WCWDwebcam,NaN,0,0,https://twitter.com/WCWDwebcam/status/10602165...
198,198,"Oroville, CA",1060191924236226561,Feather: Running http://whatsrunning.billdurr....,2018-11-07 15:27:06+00:00,NaN,whats_running,NaN,0,0,https://twitter.com/whats_running/status/10601...
199,199,"Oroville, CA",1060056825175961600,The sunset the other night on my drive home fr...,2018-11-07 06:30:16+00:00,NaN,SeanSullivan_23,NaN,0,0,https://twitter.com/SeanSullivan_23/status/106...
200,200,"Oroville, CA",1060010687685160960,Feather: Running,2018-11-07 03:26:56+00:00,NaN,whats_running,NaN,0,0,https://twitter.com/whats_running/status/10600...

In [29]:
cities.drop_duplicates(subset ="id", 
                     keep = 'first', inplace = True) 
cities.shape

(1809, 11)

In [30]:
cities.head()

,tweet_count,City,id,tweet_text,timestamp,hashtags,username,mentions,rewtweets,replies,link
0,0,"Paradise, CA",1066843491555205120,"Lord Farquad Quad Squat Squad @Chico, Californ...",2018-11-25 23:58:04+00:00,NaN,areoandmilk,NaN,0,0,https://twitter.com/areoandmilk/status/1066843...
1,1,"Paradise, CA",1066842521601400832,winter edition #queenadailypic released. @Soda...,2018-11-25 23:54:12+00:00,#queenadailypic,leenathequeena,NaN,0,0,https://twitter.com/leenathequeena/status/1066...
2,2,"Paradise, CA",1066841740060098562,Drinking a Def Leppard Pale by @ElysianBrewing...,2018-11-25 23:51:06+00:00,NaN,geradellsworth,@ElysianBrewing @Golden1Center,0,0,https://twitter.com/geradellsworth/status/1066...
3,3,"Paradise, CA",1066841178782482433,"The forgotten. #LimeBike #Reno @Reno, Nevada h...",2018-11-25 23:48:52+00:00,#LimeBike #Reno,alittlegordie,NaN,0,0,https://twitter.com/alittlegordie/status/10668...
4,4,"Paradise, CA",1066839617196961792,SSCC is United and moving Forward !!! The powe...,2018-11-25 23:42:40+00:00,#heritageoffaith,LesSimmons,@sscc7710,1,0,https://twitter.com/LesSimmons/status/10668396...

In [31]:
cities.to_csv('./data/cities_clean.csv', index=False)

In [32]:
cities[(cities['tweet_text'][0:].str.contains(pat='fire') == True)]

,tweet_count,City,id,tweet_text,timestamp,hashtags,username,mentions,rewtweets,replies,link
26,26,"Paradise, CA",1066755091049279488,THANK YOU calfire . . . . . #flyinghorsedesign...,2018-11-25 18:06:47+00:00,#flyinghorsedesigncom #sunset #picoftheday #lo...,heywoodphotog,NaN,0,0,https://twitter.com/heywoodphotog/status/10667...
27,27,"Paradise, CA",1066752850011803650,I have never felt so honored and grateful to s...,2018-11-25 17:57:53+00:00,NaN,amaze_elle,NaN,0,1,https://twitter.com/amaze_elle/status/10667528...
28,28,"Paradise, CA",1066730858403569664,Camp fire closure in #Oroville on Hwy 70 Both ...,2018-11-25 16:30:30+00:00,#Oroville #traffic,TotalTrafficSMF,NaN,0,0,https://twitter.com/TotalTrafficSMF/status/106...
33,33,"Paradise, CA",1066524560273620997,Camp fire closure in #Oroville on Hwy 70 Both ...,2018-11-25 02:50:44+00:00,#Oroville #traffic,TotalTrafficSMF,NaN,0,0,https://twitter.com/TotalTrafficSMF/status/106...
38,38,"Paradise, CA",1066501811522162688,"There is no one image, no single story that co...",2018-11-25 01:20:21+00:00,#campfire,amlikethewind,@JMichaelsNews @weatherchannel,1,0,https://twitter.com/amlikethewind/status/10665...
...,...,...,...,...,...,...,...,...,...,...,...
51,51,"Oroville, CA",1064642150170673152,At a Red Cross relief center people are postin...,2018-11-19 22:10:43+00:00,#campfire,amlikethewind,@weatherchannel @wunderground,0,0,https://twitter.com/amlikethewind/status/10646...
112,112,"Oroville, CA",1062713176490414080,Another deployment to a fire evacuee shelter i...,2018-11-14 14:25:40+00:00,NaN,cas_a_diddle,NaN,0,0,https://twitter.com/cas_a_diddle/status/106271...
137,137,"Oroville, CA",1061836090825474048,Poor air quality. Sad stories in #northerncali...,2018-11-12 04:20:26+00:00,#northerncalifornia #califirefighters,Antoine_Noble,NaN,0,0,https://twitter.com/Antoine_Noble/status/10618...
146,146,"Oroville, CA",1061672823767343105,http://sutterb.college this is what was said c...,2018-11-11 17:31:40+00:00,#campfires #buttecountyfire,kisha_vazquez,NaN,0,0,https://twitter.com/kisha_vazquez/status/10616...
182,182,"Oroville, CA",1060708065975115776,#NatchezFire unofficial new fire report; detai...,2018-11-09 01:38:04+00:00,#NatchezFire #YubaCounty,CaliFireBot,NaN,2,0,https://twitter.com/CaliFireBot/status/1060708...

### Pre-fire

In [22]:
paradise_pre = pd.read_csv('./data/paradise_pre.csv')
butte_pre = pd.read_csv('./data/butte_pre.csv')
chico_pre = pd.read_csv('./data/chico_pre.csv')
magalia_pre = pd.read_csv('./data/magalia_pre.csv')
oroville_pre = pd.read_csv('./data/oroville_pre.csv')

In [23]:
pre = pd.concat([paradise_pre, butte_pre, chico_pre, durham_pre, magalia_pre, oroville_pre])
pre.shape

(809, 11)

In [24]:
pre.drop_duplicates(subset ="id", 
                     keep = 'first', inplace = True) 
pre.shape

(342, 11)

In [25]:
pre.drop_duplicates(subset ="id", 
                     keep = 'first', inplace = True) 
pre.shape

(342, 11)

In [27]:
pre.to_csv('./data/pre-fire.csv', index=False)

In [29]:
check_dups = pd.read_csv('./data/pre-fire.csv', index_col=0)

In [30]:
check_dups.shape

(342, 10)

In [31]:
check_dups.drop_duplicates(subset ="id", 
                     keep = 'first', inplace = True) 
check_dups.shape

(183, 10)

In [32]:
check_dups.to_csv('./data/pre-fire.csv', index=False)

In [33]:
check_dups.head()

,City,id,tweet_text,timestamp,hashtags,username,mentions,rewtweets,replies,link
tweet_count,,,,,,,,,,
0,"Paradise, CA",1059596149198348289,#river #nevadacity #visitnevadacity #landscape...,2018-11-05 23:59:42+00:00,#river #nevadacity #visitnevadacity #landscape...,RHMImages,NaN,0,0,https://twitter.com/RHMImages/status/105959614...
1,"Paradise, CA",1059595878154059777,"If this is you, your computer might be at risk...",2018-11-05 23:58:38+00:00,#alienware #hp #laptop #asus #acer #lenovo #vi...,Love2fix916,NaN,0,0,https://twitter.com/Love2fix916/status/1059595...
2,"Paradise, CA",1059594896544133120,"When We Stand Together @Folsom, California htt...",2018-11-05 23:54:44+00:00,NaN,erich13,NaN,0,0,https://twitter.com/erich13/status/10595948965...
3,"Paradise, CA",1059594573066973184,"Again, for those that asked: first weekend vs....",2018-11-05 23:53:27+00:00,#YoungFrankenstein,MadRyantist,NaN,0,0,https://twitter.com/MadRyantist/status/1059594...
4,"Paradise, CA",1059593720545398786,"1.5 magnitude #earthquake. 28 km from Chester,...",2018-11-05 23:50:03+00:00,#earthquake #UnitedStates,QuakesToday,NaN,0,0,https://twitter.com/QuakesToday/status/1059593...